### ISSUE TITLE
Metafeild not displaying on Storefront

### ISSUE THREAD

**Issue by Candice-Leif** [husseyexplores/poshify-utilities#16]
One product on our storefront is not displaying the 3rd product for both "Pair" and "recommended" this is the only product that seems to be having this issue.
Reached out to Shopify and they cannot see and error with the product on their end. 
Product on live:
https://leifproducts.com/collections/gifting/products/gift-wrap-set-limited-edition-holiday-with-evi-o

Screengrab attached of products metafeild settings.
<img width="1297" alt="Screen Shot 2022-10-10 at 4 31 56 pm" src="https://user-images.githubusercontent.com/115445896/194803982-b65a4e52-cf66-4154-ab8e-716df82fb719.png">

**Comment by husseyexplores** [comment]
"You may also like" (recommended?) is showing the 3rd product.
I'm not sure what's the issue with `pair.product3`. You can always just echo out the metafield data (product handle) to see if the metafield is showing up.

![image](https://user-images.githubusercontent.com/38628704/194831007-49149b47-9ce7-41fd-b70a-1573f1a0fbf2.png)

Alternatively, you can use native Shopify metafields. There is a `product_reference` type and `list.product_reference` types available that support selecting specific products directly.

This extension (Poshify) is under development to support new metafield types. No ETA on when will it be released.

**Comment by Candice-Leif** [comment]
Strange,  I see the 3rd product on "You May Also Like" for a split second then it drops off, which browser are you using?
<img width="1336" alt="Screen Shot 2022-10-11 at 9 52 56 am" src="https://user-images.githubusercontent.com/115445896/194964048-25909a5b-c0e6-430b-9d5b-a0bbc251d78a.png">
Will look into moving over to Shopify metafeilds, it's probably easier to have them all within the product for editing purposes.

**Comment by husseyexplores** [comment]
I'm also seeing the flickering of the third product of "You may also like". It's a bug in your code, somewhere along here:
![2022-10-11_20-49](https://user-images.githubusercontent.com/38628704/195139735-f44878eb-12b7-4828-a731-ac9280fff3e8.png)

I can't help much more here. I'm not sure what's happening with the `pair` metafield.
Most likely have the wrong product handle, because it seems to be working on other products.

Good luck!

**Comment by husseyexplores** [comment]
I'm also seeing the flickering of the third product of "You may also like". It's a bug in your code, somewhere along here:

![2022-10-11_20-49](https://user-images.githubusercontent.com/38628704/195140555-06f716f6-1905-47a3-9f1b-b36ab56c73c0.png)

I can't help much more here. I'm not sure what's happening with the pair metafield.
Most likely you have the wrong product handle because it seems to be working on other products.

Good luck!
