### ISSUE TITLE
Error with creating new metafield - "Server error: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by lizp22** [husseyexplores/poshify-utilities#18]
Hi,
I want to create new metafields, saved as 'string (deprecated)', but this error comes up "Server error: Unexpected end of JSON input".

See attached image.

<img width="932" alt="Screenshot 2023-02-24 at 11 52 34" src="https://user-images.githubusercontent.com/126252687/221173365-7f0102d5-c7e0-4dd6-a8fc-c78635e26161.png">

**Comment by husseyexplores** [comment]
Did you try refreshing? I guess the auth token is expired and the server is erroring out.

And also, try changing the "save as" type to the new "Single line text" and see if it works.

I've just tried creating "String (depricated)" type on a couple of stores, and it's working fine so far.

Or if you're savvy enough, maybe take a look the network tab in the browser devtools and what's the error.

**Comment by husseyexplores** [comment]
If all fails - I could also inspect it myself if you're willing to provide me collaborator access to test this issue.

**Comment by lizp22** [comment]
Thanks for the quick response. It seems to be a Shopify login issue, when I try to update the metafield a login box for Shopify pops up, even though I am already logged in.

**Comment by husseyexplores** [comment]
Yes, it's the auth token issue.  For some reason, it's not there.
It's Shopify, so we don't have control over the code.
Unfortunately, I can't help you here unless I have collaborator access and debug it myself. If it's possible for you and you're willing to invite me as a collaborator, let me know anytime.

**Comment by nhaiduy** [comment]
Hi, I'm also having this issue. Here's a video to show the problem [LINK](https://www.berrycast.com/conversations/3af26a3e-6985-5676-adfa-a1c9ae0077f4)

I'd be happy to invite you as a collaborator. Please advise

**Comment by husseyexplores** [comment]
@nhaiduy I don't see anything wrong.
The issue where you had to remove the blank product, will be removed in a couple of days (in the next release)
I'm aware of that.

The error is most likely due to missing auth tokens and would be happy to debug it as it'd help others as well.

The store URL is `impack-co.myshopify.com`, correct? Can I send the collaborator request?

**Comment by nhaiduy** [comment]
Hey, yes that’s the store URL and I’ve just accepted the request, thank you!

**Comment by husseyexplores** [comment]
A new version has been released and the issue has been patched.

Thanks, @nhaiduy! For letting me have the collab access to debug the issue!

PS: Shopify is currently using two different admin URLs:
- `your-store.myshopify.com` (old - will be replaced soon)
- `admin.shopify.com/store/your-store` (new - all merchants are gradually being migrated to use this)

The issue was happening on the old URL - now fixed.
